swagger.yaml

Added room geometry support

---

swagger.yaml

Added leaflet bounds

---

swagger.yaml

Added support for page transitions

---

swagger.yaml

Bugfix 54 polygon format

---

swagger.yaml

Fixed format

---

swagger.yaml

Renamed ExhibitionContentVersion to ContentVersion

Added group content version

---

swagger.yaml

Added roomid array to ContentVersion

---

swagger.yaml

Feature 69 rfid antennas

---

swagger.yaml

Feature 71 device group mqtt messages

---

swagger.yaml

Feature 73 stored files api

---

swagger.yaml

Feature 75 group contents by content

---

swagger.yaml

Changed layout widget type to enum

---

swagger.yaml

Added support for defining room's color

---

swagger.yaml

Feature 84 group content version device group id filter

---

swagger.yaml

Added support for device orientation

---

swagger.yaml

Bugfix 88 missing mqtt objects

---

swagger.yaml

Added MapView

---

swagger.yaml

Added sub layout to spec

---

swagger.yaml

Added support for device page order

---

swagger.yaml

Moved page order to correct place

---

swagger.yaml

Added id and name to ExhibitionPageEventTrigger object

---

swagger.yaml

Added html type

---

swagger.yaml

Bumped spec

---

swagger.yaml

Added support for svg resource type

---

swagger.yaml

Added support for resource mode

---

swagger.yaml

Added support for executeWebScript actions

---

swagger.yaml

Feature 113 remove page order from device

---

swagger.yaml

Removed device index page

---

swagger.yaml

Added support for specifying visitor session language

---

swagger.yaml

Added support for visitor session end action

---

swagger.yaml

Added support for user session settings

---

swagger.yaml

Added content container

---

swagger.yaml

Added support for changing device group visitor session start strategy
